### ISSUE TITLE
Contao Manager: The Contao version could not be determined

### ISSUE THREAD

**Issue by SchwalenbergJe** [contao/contao-manager#201]
Hallo.
Ich habe aktuell ein Problem mit der aktuellen Version des Contao Managers (1.0.0-beta13) in Verbindung mit der Contao Version 4.4.8 auf einem Host Europe Hosted Server.

Das Contao CMS läuft wunderbar, doch während der Systemprüfung bei der Installation des Managers erscheint folgende Fehlermeldung:

> ERROR 500 The Contao version could not be determined
> The console returned unexpected content when asked for the Contao version. Please check the output for more information:
> 
> 
> dir=$(d=${0%[/\\]*}; cd "$d" > /dev/null; cd "../contao/manager-bundle/bin" && pwd)
> 
>  See if we are running in Cygwin by checking for cygpath program
> if command -v 'cygpath' >/dev/null 2>&1; then
>  Cygwin paths start with /cygdrive/ which will break windows PHP,
>  so we need to translate the dir path to windows format. However
>  we could be using cygwin PHP which does not require this, so we
>  test if the path to PHP starts with /cygdrive/ rather than /usr/bin
> if [[ $(which php) == /cygdrive/* ]]; then
> dir=$(cygpath -m "$dir");
> fi
> fi
> 
> dir=$(echo $dir | sed 's/ /\ /g')
> "${dir}/contao-console" "$@"

Kann mir hier jemand weiterhelfen?

**Comment by aschempp** [comment]
Kann es sein dass du Contao manuell hochgeladen hast, in Verwendung von Windows? Die Composer-Binaries scheinen falsch zu sein.

**Comment by fritzmg** [comment]
This problem occurs frequently on the forum and it is not related to the operating system.

In general, the Contao Manager should not be designed in a way that it needs to rely on determining the Contao Version. If anything goes wrong during a package update for example, the Contao Manager renders itself useless to the user, since he cannot even attempt to fix the problem by simply running another package update (or install in the future) again.

**Comment by fritzmg** [comment]
This is still a huge problem. The Contao Manager should _not_ rely on a functioning Contao/Symfony installation. Due to the recent bug introduced in Symfony `3.4.7` (and `4.0.7`) (see https://github.com/contao/manager-bundle/issues/61 & https://github.com/symfony/symfony/pull/26337) anyone who updates before adding the conflict in the `composer.json` will end up with a non-functioning Contao Manager.

**Comment by aschempp** [comment]
I agree it *should not* rely on that, but it currently does. There's no easy fix for it yet, but I'm working on that 😞

**Comment by aschempp** [comment]
implemented in version 1.1.0

**Comment by fritzmg** [comment]
🎉
