### ISSUE TITLE
Possible to use Contao Manager without update check after login?

### ISSUE THREAD

**Issue by V15** [contao/contao-manager#352]
Right now contao.org is not reachable.
I guess this is the reason why I get an error when I try to use the Contao Manager:

- PHP-Webprozess - OK
- Serverkonfiguration - OK
- PHP Kommandozeilen-Programm - OK
- Updates für den Contao Manager - Die Prüfung ist aufgrund einer unerwarteten Server-Antwort fehlgeschlagen.
- Composer-Umgebung - Warten
- Contao-Installation - Warten

Is this necessary?
Right now the Manager is not usable without this check.

But is this check (or the connection to the update server) needed if I only want to clear the cache or install an application?

Otherwise it would be nice if I could skip this check and use the Contao Manager anyway.

**Comment by aschempp** [comment]
The update check is done on EVERY launch of the Manager, because we don't want to maintain multiple versions to be run in the wild. I agree this is somewhat cumbersome if the contao.org servers are down, but it does not really make sense to me to invest any work into a check/bypass that should never ever happen again… 😉

**Comment by V15** [comment]
Thanks for the explanation, thats understandable.

**Comment by V15** [comment]
Thanks for the explanation, thats comprehensibly.
