### ISSUE TITLE
Add editor for conflicts

### ISSUE THREAD

**Issue by dmolineus** [contao/contao-manager#381]
As the recently issue with doctrine/dbal shows, sometimes conflicts occurs. It would be useful for Contao Manager users to manage the conflict entries in the CM.

**Comment by Toflar** [comment]
Even better than giving the users the option to manage conflicts would be to make sure, they don't even have to worry about it (in the best case). I'm thinking about a `contao/conflicts` where we have two branches (4.4 and master or so) that contains the conflicts. We could require this in the managed edition and manage conflicts for our users. In the doctrine/dbal case we could've added a conflict and nobody would have noticed :)

But still, maybe sometimes you need to be able to manage conflicts for third party bundles etc.

**Comment by aschempp** [comment]
@leofeyer I propose a repository `contao/manager-conflicts`, which should be required by the `contao/manager-bundle`. The versioning will be different than core, or better said no versions, so it will not be part of the monorepo. It should only use branches for every version of Contao.

I'm strongly against any manual editor features, if you need that, use FTP access. I'm closing this, but be aware that this topic will be discussed on our next dev meetup to find a solution.

**Comment by leofeyer** [comment]
Not sure about an external package, because conflicts should be added in the root composer.json to make sure they are applied.

**Situation A**

contao/core-bundle 4.6.13
bundle has new conflict: doctrine/dbal 2.9.1

-> Composer might install contao/core-bundle 4.6.12 together with doctrine/dbal 2.9.1

**Situation B**

contao/core-bundle 4.6.13
root has new conflict: doctrine/dbal 2.9.1

-> Composer will never install doctrine/dbal 2.9.1

Do you know what I mean?

**Comment by aschempp** [comment]
Thats not gonna happen. That's why we don't add the conflict to the core-bundle, but to a separate bundle. That bundle does not have versions, just branches, so Composer is always forced to install the latest version (and respect the conflicts).
