### ISSUE TITLE
Composer Logfile shouldn't self-delete after finishing queue

### ISSUE THREAD

**Issue by Nightwing0815** [contao/contao-manager#449]
Version 4.8.x

I think, composer's logfile (= **composer-install.out.log** ) shouldn't self-delete after finishing the queue. So you can have look afterwards, which components gets an update. And it's imho better for copying text out, for example for a forum post, when something went south.

ToM

**Comment by Nightwing0815** [comment]
@fritzmg oops... doh! leo was faster with correcting it.
@leofeyer thanks for movin to right direction and sorry for opening in wrong one :-)

**Comment by aschempp** [comment]
The files are *always* deleted after you clicked on "close" in the popup. If you need the log, you can copy it from the Contao Manager.

**Comment by fritzmg** [comment]
Imho for easier community support it would make sense to only overwrite the .out file - and not delete it after the tast window is closed. In the forum I often have to ask for the console output - but usually people don't have it any more, because they do not know that the console output shows them what went wrong.

**Comment by Nightwing0815** [comment]
Additionally to fritzmg, xchs and I have the same idea: [https://community.contao.org/de/showthread.php?75842-Bei-der-Ausf%C3%BChrung-des-Skriptes-ist-ein-Fehler-aufgetreten&p=510197&viewfull=1#post510197]

**Comment by aschempp** [comment]
In 1.3 the log files are archived in the `contao-manager` folder 😎
