### ISSUE TITLE
Anlegen eines Benutzers unter PHP7.4 funktioniert nicht

### ISSUE THREAD

**Issue by webwerkwien** [contao/contao-manager#512]
Contao Manager 1.2.2

Installing C4.8 you can not establish a user in CM, it ends with following error:
ERROR 500 Error: Uncaught TypeError: Return value of Symfony\Component\Security\Core\Encoder\NativePasswordEncoder::encodePassword() must be of the type string, null returned in phar:/// ... /contao-manager.phar.php/vendor/symfony/security-core/Encoder/NativePasswordEncoder.php:71

If you use another PHP-version instead of 7.4 it works, also see https://community.contao.org/de/showthread.php?76824-Fehler-beim-Erstellen-des-CM-Benutzerkontos&p=517267#post517267

Kind regards!

**Comment by ReneLuecking** [comment]
I haven't checked it, but it seems to correlate with the change of the password constants in PHP 7.4: https://www.php.net/manual/de/migration74.incompatible.php#migration74.incompatible.core.password-algorithm-constants

If the application uses the old constant values directly instead of the constants itself it would break with PHP 7.4 and `password_hash` (which is used by `NativePasswordEncoder::encodePassword()`) returns `null`.

**Comment by ReneLuecking** [comment]
The problem lies in the combination of how the contao-manager.phar is built and how the symfony cache works. When executing the cache:warmup command, symfony creates the file api/Resources/cache/ContainerXYZ123/getSecurity_EncoderFactory_GenericService.php (the actual folder name of ContainerXYZ123 can differ). It contains a return statement and the last value of the arguments array of the return statement is the value of the password hashing algorithm constant defined in the config.yml (bcrypt). If the contao-manager.phar and therefore the cache are build under PHP < 7.4 it is the number 1. If the cache is build with PHP >= 7.4 it is the string 2y. The current version of the contao-manager.phar was built with PHP < 7.4 so it crashes with the error mentioned above. If the contao-manager.phar would be built with PHP >= 7.4 it would be the other way round.

**Comment by ReneLuecking** [comment]
Is there any reason to use bcrypt as hashing algorithm? If not, i would recommend to replace `bcrypt` with `native` in the `config.yml`. If using `native`, Symfony will not cache the password hashing algorithm and will choose the algorithm based on the PHP version while creating a new user: Argon2id for PHP > 7.3, argon2i for PHP 7.2 and otherwise bcrypt. Already existing password will be still valid, because the algorithm is saved in the password hash.

**Comment by aschempp** [comment]
Not sure what `native` is and why `bcrypt` does not work for you, but we'll update to `auto` which is the recommended option. Thanks for investigating this!
https://symfony.com/doc/current/reference/configuration/security.html#using-the-auto-password-encoder
