### ISSUE TITLE
Configurable cloud resolver

### ISSUE THREAD

**Issue by Coding-Kiwi** [contao/contao-manager#552]
Hi,

wäre es möglich, die momentan noch hard-coded `private const API_URL = 'https://composer-resolver.cloud';` konfigurierbar zu machen? Das würde ermöglichen, dass man eigene resolver server einrichten kann.

=== english ===

would it be possible to make the currently hard-coded `private const API_URL = 'https://composer-resolver.cloud';` configurable? This would allow people to roll out their own resolver servers.

**Comment by aschempp** [comment]
I think this has been discussed before, but honestly I don‘t see a point in this. If you are capable of running a custom resolver, I would argue you should probably not use the Contao Manager at all? 
Nonetheless, you can always compile your own phar with a different URL, have you tried that?

**Comment by Coding-Kiwi** [comment]
@aschempp In my case we have an external, managed server for web projects where we can't use composer because high-RAM processes get killed, therefore we use the cloud resolver and contao manager for easier accessability.

Yes I could compile my own phar but that would mean that after every update of the contao manager, I would have to compile the phar again and manually distribute it to all web projects since the auto-update functionality of the manager would be useless at that point.

Furthermore, allowing custom cloud resolvers would take some load off the public one where you sometime have to wait half an hour until the job even starts and then another 30 minutes when doing a dry-run first ^^

It just thought a small config option isn't a huge thing to implement, but that is your decision.

**Comment by leofeyer** [comment]
I like the idea.

**Comment by aschempp** [comment]
> Yes I could compile my own phar but that would mean that after every update of the contao manager, I would have to compile the phar again 

Yes, because you have to make sure your Composer Cloud is compatible. The API to the cloud is not stable and can be changed in any version (one of the reasons we _force_ updates of the Manager).

> and manually distribute it to all web projects since the auto-update functionality of the manager would be useless at that point.

Not true, you simply run your own auto-update functionality/server. Same as the Composer Resolver, its simply changing a URL in a static variable.

> Furthermore, allowing custom cloud resolvers would take some load off the public one 

That might be true, but I would argue it to be rather insignifficant (not 1% of Manager users would run their own Cloud Resolver). And it would probably add some burden on all of us to maintain a stable API or communitcate/discuss how the Cloud works internally?

---

I usually compare these things to Apple/iOS vs Android (my opinion on that!). Apple does not add features, if they can't be added right. They did not add multitasking initially, because it did break performance and battery life. Android always had it, and it was problematic for a long time. Apple added it later by "freezing" processes, and Android soon switched to that behavior (as far as I know). I see the manager as an _Apple project_: I don't like adding features that are only a fix for a deeper problem.

What you're actually trying to do (if I understand correctly) is to prevent wait-time in the Composer Cloud. The _correct_ solution (my opinion!)  is not to run your own cloud resolver, but to improve the public one – for example by auto-scaling the Docker containers. Thats something we're discussion, but it's technically difficult, time consuming and possibly expensive.
Another thing is to improve Composer to use way less memory, that's where the Contao developers are already working on (see https://github.com/composer/composer/pull/8275, https://github.com/composer/composer/pull/8295, https://github.com/composer/composer/pull/8850).
