### ISSUE TITLE
Contao Manager 1.4.3: package list shows "unknown version" and outdated version updates

### ISSUE THREAD

**Issue by Smurffson** [contao/contao-manager#646]
Contao Manager 1.4.3 shows **some** packages as "unknown version" in menu "package". And on one it reports a wrong update version.
In my current installation following packages are affected:

- Contao 4.9.13
- markocupic/import-from-csv-bundle
- do-while/contao-backupdb-bundle

Bundle "terminal42/contao-password-validation" is installed in version 1.0.7 and CM shows me an available update to version 1.0.0.

I didn't upgrade my other Contao 4.x installations yet.

What I tried so far:
- Clearing production cache 
- Clearing composer cache

**Comment by dp-designpilot** [comment]
I have the same Problem, aschempp can you fix this ?

**Comment by itnomic** [comment]
Same problem on all my websites with Contao Manager 1.4.3. No Problems before update

**Comment by soweit-ok** [comment]
The same bug in all my installations since Contao-Manager update to 1.4.3. update of individual bundles still works. If several bundles are updated at the same time, the database can no longer be updated with the install tool. The log file then contains dbal error messages (no database connection).

I tried to fix the dbal driver to version 12.1 in composer.lock. Because of this symfony bug in version 13.0. Unfortunately it was unsuccessful. I couldn't find a cause of the "Unknown Version" bug. The composer.lock file lists the correct installed version numbers. Packagist references and Github URLs are also correct.

It doesn't seem like a good idea to me that the Contao Manager update is forced and won't start otherwise. Why is it necessary? Therefore, all Contao installations are affected by every bug and, especially in the case of large projects with many installed bundles and individual solutions, the analysis can be time-consuming to determine whether the cause is a own bug  or a bug in the Contao core or a bug in an expansion bundle.

**Comment by mp-itconsulting** [comment]
I also have the same problem since forced update to 1.4.3.
I also think that is not the best idea or even required to force the update and otherwise refuse from starting. Update should be optional! There are other options in case an update is really required.

**Comment by aschempp** [comment]
Please be aware that this is only a display problem. Package installation is not affected, so any package-related isssues should be a separate ticket.

**Comment by kgollmer** [comment]
Just to be clear: will this issue affect updates I'm trying to run (install outdated versions if I tried to update a package)?

**Comment by mlwebworker** [comment]
No, is only a display problem.
