### ISSUE TITLE
Trying to upgrade from Contao 3.5.40 to Contao 4 using Contao Manager 1.4.10

### ISSUE THREAD

**Issue by Sanderadio** [contao/contao-manager#667]
Hi,
I'm trying to upgrade from Contao 3.5.40 to Contao 4 using Contao Manager 1.4.10. I get all green checkmarks except for the last. It reads: "Contao Installation
Contao version 3.5.40 is not compatible with the Contao Manager, please update your installation manually."
What could be wrong? How do I update manually? I don't much about Composer. I just moved my website to the hosting provider ionos.com since it's a Contao Premium Partner

**Comment by aschempp** [comment]
The Contao Manager can only _manage_ a Contao 4 installation. A major version upgrade must be done manually, mostly by installing a new, separate Contao 4 (through the Contao Manager) and copying files and database. 

There are extensive manuals and videos online if you search for it, e.g. at https://contao-academy.de/blog/update-contao-3-auf-contao-4 (if you speak german). 

For any further help, please contact the Community Forums or our Slack channel (https://to.contao.org/support), since GitHub is only for bug and feature tracking.

**Comment by Sanderadio** [comment]
Ah I didn't know. Thank you. Google Translate does a great job in translating that document, my German is a little "versinkt" 😉 Consider this as a feature request. But I managed to install it in an empty directory, only have to figure out if there's a successor to OnePageWebsite with moo_smoothScroll because my site isn't running just yet. I get a critical error. Will look/ask for it in the Community Forums. Thank you so much for your prompt reply, Andreas!
